### ISSUE TITLE
Add control of Landroid, is it possible?

### ISSUE THREAD

**Issue by maartendamen** [weweave/landroid-bridge#1]
Thank you for your work. 
Would it be possible to add control of the Landroid S? (for example send the start command)

I would like to make rules based on weather condition, my irrigation system etc.

**Comment by virtualzone** [comment]
Thanks for your hint! Yes, I am already working on update commands and will commit the functionalities in a few days.

**Comment by weweave** [comment]
It is now possible to start/stop the mower and to set the rain delay/time extension via both MQTT and REST. I will add more update functionalities shortly.

**Comment by bebben88** [comment]
Nice binding! One question, when publishing to the mower. What message to send? I understand to send to the topic landroid/start but should i send ON? Could you please update your readme with a example item for that.

**Comment by virtualzone** [comment]
The payload of the start/stop MQTT message is not being considered, so you can just send any message or an empty message to the topic landroid/start and landroid/stop. I will update the readme with more concrete examples shortly. Thanks for your feedback!

**Comment by bebben88** [comment]
I cant get it to work. This is my openhab items. Start stop doesn't work. Time extension works however.
I have changed the base topic to "mower" btw. I cant start it with an empty message from node red either to the topic.
`Switch Landroid_start_stop "Start/Stopp" <switch> (gMower) {mqtt=">[morgoth:mower/start:command:ON:true],>[morgoth:mower/stop:command:OFF:true]"}
Number Landroid_time_extension "Gräsklippare: Klipptid [%d %%]" (gMower) {mqtt="<[morgoth:mower/status/timeExtension:state:default],>[morgoth:mower/set/timeExtension:command:*:default]"}
`

**Comment by virtualzone** [comment]
I have not integrated the start/stop commands with my OpenHAB installation yet. I will do this shortly and let you know. In the meantime, you could check the following:
Do both the MQTT broker and the bridge receive the MQTT commmands?
You could try publishing the start/stop message directly using the mosquitto_pub command line tool and check if this works.
Have you integrated the reading bindings into your openHAB installation successfully?

**Comment by bebben88** [comment]
The broker recieves it, verified with nodered. The bridge dosent receive when i publish to mower/start.
Both the broker and bridge recives the timeextension. Tested with mosquitto pub. ( mosquitto_pub -t 'mower/start' -m '') Same results. Every reading binding works very well. So i dont understand why it dosent work.

**Comment by bebben88** [comment]
It's me who should be thanking for the great work with the bridge. I just
put out the mower for the season and then I saw your bridge. Perfect.

Den sön 22 apr. 2018 11:23Heiner <notifications@github.com> skrev:

**Comment by weweave** [comment]
We've added support for changing the mower's schedule (see examples in the readme).
