### ISSUE TITLE
npm install fails to pull in sqlite

### ISSUE THREAD

**Issue by tmolberg** [weweave/landroid-bridge#12]
npm is throwing off errors when its trying to poll out a package,

Any idea one how to get around this one? It manages to complete but while running the bridge its throwing off other errors which I corrolates with the missing package

`Unhandled exception: TypeError: self.adapter.setState is not a function`

``
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/node-v48-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@4.0.0 and node@6.13.1 (node-v48 ABI, glibc) (falling back to source compile with node-gyp)
``

Edit: Running openhabian. Also tried downloading the tar file manually without any luck. Still getting 403

EDIT2: getting the same error as above when trying to run it through the docker container
`
Loading config from /usr/src/app/config.json
Dev mode = undefined
Starting Landroid Bridge...
Setting port to 3000...
Connecting to MQTT Broker...
Adding static files path /usr/src/app/www
Skipping scheduler initialization (not enabled)
Initializing Landroid Cloud Service...
Unhandled exception: TypeError: self.adapter.setState is not a function
Received exit signal...
Closing http listener...
`

**Comment by DonStefano** [comment]
Getting the same error and output, when starting landroid-bridge via cmdline:
`node dist/server.js`
 Output is:
`Loading config from /var/www/landroid-bridge/config.json
Dev mode = undefined
Starting Landroid Bridge...
Setting port to 3333...
Connecting to MQTT Broker...
Adding static files path /var/www/landroid-bridge/www
Creating SQLite database at /var/www/landroid-bridge/scheduler.db
Successfully connected to MQTT Broker!
Initializing Landroid Cloud Service...
Unhandled exception: TypeError: self.adapter.setState is not a function`

**Comment by virtualzone** [comment]
When running `npm install` and npm can't download a pre-built sqlite3 package for your architecture, it normally tries to build sqlite3 from source. Make sure you have the necessary build tools installed (on Debian based systems, i.e. https://packages.debian.org/de/stretch/build-essential) and try to run `npm install` again.
