### ISSUE TITLE
Use payloads in mqtt

### ISSUE THREAD

**Issue by olskar** [weweave/landroid-bridge#13]
Hello!

I am trying to implement your code in home assistant as mqtt.

The thing is it needs a command_topic and then the payload decides what should happend, for example start and stop.

In your code there are instead two topics, and no payload involved; landroid/set/start and landroid/set/stop

Would it be possible to change this so a payload with start to landroid/set/ starts the device and stop stops it?

**Comment by virtualzone** [comment]
Hi @olskar,
I've added a new MQTT topic set/mow which accepts the payloads "start" and "stop". Hope this helps for your issue.
