### ISSUE TITLE
Additional Status 33, Percent Circle from old App

### ISSUE THREAD

**Issue by ralf-koe** [weweave/landroid-bridge#14]
Not really issues, rather questions.

I get from landroid-bridge Status 33  as "undefined", seems to be missing in the bridge.

Additional I like the circle (0-100%) within the old app regarding the overall work per day. 
Is this information calculated or somewhere available in the interface?

P.S: Very nice work! I add my WR106SI easy to [symcon](https://www.symcon.de/forum/threads/37905-Worx-Landroid-CSV-wie-Werte-in-einzelne-Variablen-schreiben?p=363128#post363128)

**Comment by ralf-koe** [comment]
Update from Eisha in roboter forum
APP_WIRE_FOLLOW_GOING_HOME = 30,
APP_WIRE_FOLLOW_AREA_TRAINING = 31,
APP_WIRE_FOLLOW_BORDER_CUT = 32,
APP_WIRE_FOLLOW_AREA_SEARCH = 33,
PAUSE = 34

**Comment by fisch3009** [comment]
Thread in roboter-forum.com
[http://www.roboter-forum.com/showthread.php?22795-Entwicklungsprojekt-Landroid-S-Windows-App&p=358518&viewfull=1#post358518](Post in Roboter-Forum.com with statuscodes)

**Comment by virtualzone** [comment]
@ralf-koe I've added the missing status codes, thanks for your hint!
Let me see if I can implement the circle / a little dashboard...

**Comment by virtualzone** [comment]
Dashboard (with percentage circle) is now available
