### ISSUE TITLE
landroid-bridge refuses to start correctly

### ISSUE THREAD

**Issue by DonStefano** [weweave/landroid-bridge#15]
when starting landroid-bridge via cmdline:
`node dist/server.js`
 I get this error message:
`Loading config from /var/www/landroid-bridge/config.json`
`Dev mode = undefined`
`Starting Landroid Bridge...`
`Setting port to 3333...`
`Connecting to MQTT Broker...`
`Adding static files path /var/www/landroid-bridge/www`
`Creating SQLite database at /var/www/landroid-bridge/scheduler.db`
`Successfully connected to MQTT Broker!`
`Initializing Landroid Cloud Service...`
**`Unhandled exception: TypeError: self.adapter.setState is not a function`**

I had posted this error message in issue #12 before, but my result is not related to sqlite installation problem. After this message I can access the web interface but there aren't any values.

**Comment by DonStefano** [comment]
The problem is still occuring. After the first error message it keeps retrying. The output is:
`
Could not finish initialization, retrying...
``Unhandled exception: TypeError: self.adapter.setState is not a function
`

**Comment by DonStefano** [comment]
I found the cause of the error by looking at the code. The exception is raised at line 46 of landroid-cloud-2.js (from iobroker.landroid-s). I can't fix the issue but this code is only executed, if the connection to the cloud is failing. So after entering the correct password, I can connect successfully and the web interface is working correctly.

**Comment by virtualzone** [comment]
Thanks for the hint! I've fixed this issue finally. Please try the latest version, it contains improved error handling and logging.
