### ISSUE TITLE
product_id: 40 Plese make an issue on git with this product id

### ISSUE THREAD

**Issue by popshansen** [weweave/landroid-bridge#22]
Thanks for the landroid-bridge.

I have an WR115MI and get this message during startup of the bridge.
Product id 40

Best regards

**Comment by virtualzone** [comment]
@popshansen The message comes from the underlying library: https://github.com/MeisterTR/ioBroker.landroid-s
Can't fix it in the bridge itself, sorry. Please open an issue there.

**Comment by MeisterTR** [comment]
It is just a notice for me that I can make a list of id's for s and m Modell, to select the m Modell
