### ISSUE TITLE
IoBrokerAdapter - product_id: 37

### ISSUE THREAD

**Issue by normen** [weweave/landroid-bridge#26]
"Plese make an issue on git with this product id" :)

It's a "Landroid-SO500i" according to the Box or a "Landroid S WR105Sl.1" according to the App "Info" section.

**Comment by virtualzone** [comment]
Hi @normen , this message is produced by the used module: 
https://github.com/MeisterTR/ioBroker.landroid-s
Can you open an issue there? Thanks!

**Comment by normen** [comment]
Done, now you just need to update the dependency to 2.5.2 if it's still compatible.

**Comment by virtualzone** [comment]
I've upgraded the dependency to 2.5.4.
