### ISSUE TITLE
product_id: 33

### ISSUE THREAD

**Issue by Hooch76** [weweave/landroid-bridge#31]
The logfile told me to create an issue here:

```
[2018-08-17T10:12:16.889] [WARN] IoBrokerAdapter - product_id: 33 Plese make an issue on git with this product id
```
Done. Do you want me to look something up?

**Comment by virtualzone** [comment]
@Hooch76, please open the issue there - the message is produced by the used library: 
https://github.com/MeisterTR/ioBroker.landroid-s
