### ISSUE TITLE
Support for new cloud enabled Model M firmware 

### ISSUE THREAD

**Issue by epideme** [weweave/landroid-bridge#35]
Landroid M has a new v5 firmware that enables cloud connection.
The bridge actually detects the Landroid but won’t start up completely.
WG796E.1 gives “product_id":11 and a lot of fully correct variables and values are returned in the debug. 
The rest of the debug string is a bit too verbose with my personal info for me to post here. 😜

**Comment by virtualzone** [comment]
@epideme Please open a ticket here: https://github.com/MeisterTR/iobroker.landroid-s
