### ISSUE TITLE
Update landroid-cloud-2.js

### ISSUE THREAD

**Issue by MeisterTR** [weweave/landroid-bridge#39]
Please update the bridge from landroid-cloud-2.js to mqtt-cloud.js and worx Config.js. The mqttcloud supports all Landroid models.

**Comment by MatziBrow** [comment]
I want to use the Landoid M500 and there tried to update, but I was not sure how to do it.
Could you Maybe explain? Thanks a lot in Advance!

**Comment by stefanlaheij** [comment]
I created a pull request for this

**Comment by virtualzone** [comment]
Thanks, I've merged the pull request.
