### ISSUE TITLE
Support Landroid M500 V2019

### ISSUE THREAD

**Issue by Tihmann** [weweave/landroid-bridge#45]
Does this software support the new Landroid M500 V2019 ?

**Comment by Janestar80** [comment]
Hi, I confirm that the bridge works for the 2019 Landroid M500 model. You will have to perform the code-change as described by contributers in closed issue https://github.com/weweave/landroid-bridge/issues/46
Be sure to recompile (npm run grunt) after applying the change!

**Comment by virtualzone** [comment]
I've merged the pull request, the new model should work out of the box now.
