### ISSUE TITLE
error during execution

### ISSUE THREAD

**Issue by perlokan** [weweave/landroid-bridge#6]
Hi,
after the first running I receive the following error:
Loading config from /usr/src/app/config.json
Dev mode = undefined
Starting Landroid Bridge...
Setting port to 3000...
Adding static files path /usr/src/app/www
Connecting to MQTT Broker...
Initializing scheduled tasks...
Server ready
Unhandled exception: TypeError: self.adapter.setState is not a function

**Comment by virtualzone** [comment]
Hi @perlokan ,
that seems to be the output of an older version. Can you pull the latest and try again?
