### ISSUE TITLE
Other weather providers supported?

### ISSUE THREAD

**Issue by olskar** [weweave/landroid-bridge#8]
Hello! Since weather underground no longer has a free api, i am curious of any other weather api is supported?

**Comment by virtualzone** [comment]
I've finally added support for Dark Sky (aka forecast.io) as a second weather provider. The forecast of Dark Sky is not as accurate, as it only supports hourly forecasts for the next 48 hours. After that, it only provides daily forecasts. However, I think that it's something we can work with.
